# Generated by Django 3.2.7 on 2021-09-28 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default='', help_text='이메일', max_length=100, unique=True)),
                ('army_num', models.CharField(default='', help_text='**-********', max_length=100, unique=True)),
                ('army_rank', models.CharField(choices=[('private', '이병'), ('first_class private', '일병'), ('corporal', '상병'), ('sergeant', '병장'), ('executive', '간부 및 장교')], default='private', max_length=50)),
                ('name', models.CharField(default='', help_text='본명', max_length=100)),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='가입일')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
