# Generated by Django 3.2.7 on 2021-10-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_status',
            field=models.CharField(choices=[('ongoing', '거래 진행 중'), ('completed', '거래 완료')], default='ongoing', max_length=30),
        ),
    ]
