# Generated by Django 3.2.7 on 2021-10-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20211008_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='useremail',
        ),
    ]
