# Generated by Django 3.2.7 on 2021-10-09 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_comment_useremail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='useremail',
        ),
    ]
