# Generated by Django 3.2.7 on 2021-09-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20210925_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='board_type',
            field=models.CharField(choices=[('pick_up', '찾아가세요'), ('request', '찾아주세요')], default='pick_up', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('else', '기타류'), ('army_uniform', '군복류'), ('running_shirts', '런닝'), ('underwear', '속옷'), ('underclothes', '내복'), ('socks', '양말'), ('shoes', '신발류'), ('towel', '수건'), ('caps', '모자류'), ('phones', '핸드폰'), ('books', '책'), ('stationery', '문방구')], default='else', max_length=20),
        ),
    ]
